### ISSUE TITLE
Edge 14 not styling shadow dom nodes

### ISSUE THREAD

**Issue by jorrete** [webcomponents/shadycss#12]
Hi,

[Example](https://gist.github.com/jorrete/645b4a3078c4ccec047ba81fe278a944)

The examples renders wrong on Edge 14.14393.
The h1 gets no styles.

Thanks!

**Comment by frankiefu** [comment]
Another example that shows it's not working correctly in Edge
https://gist.github.com/frankiefu/8d1a06bbfeb4a1142adfdee1b0190099

**Comment by tuespetre** [comment]
I've found that I need to import `StyleTransformer` in order for things to work.

Example, using ES2015 that transpiles via Browserify/Babelify:

```
import { StyleTransformer } from '../bower_components/shadycss/src/style-transformer.js';

const initialTemplate = makeTemplate `
    (your css and html here)
`;

ShadyCSS.prepareTemplate(initialTemplate, 'my-component');
StyleTransformer.dom(initialTemplate, 'my-component');
```

The reason we have to do this seems to be that `prepareTemplate` passes in the template's `content` property to `StyleTransformer`, which then essentially no-ops because `children` is undefined on `DocumentFragment`. If `prepareTemplate` would pass in the actual template instead of its `content` property, I would imagine things would be correct.

**Comment by tuespetre** [comment]
Upon further investigation, it seems that IE and Edge do not implement [the `ParentNode` interface] for `Document` and `DocumentFragment`. [I have now written a polyfill for it](https://gist.github.com/tuespetre/f91b91bfd4dabab04e57a6db187c0c34) and I no longer need to use `StyleTransformer`.
