### ISSUE TITLE
Alternative for prepareTemplate when using innerHTML with template string?

### ISSUE THREAD

**Issue by lukasoppermann** [webcomponents/shadycss#19]
Hey,

so my element is all within one js file. I am not using a `<template>` tag but rather:

```
var element = `
<style>
     :host{
          ...
`;

let shadowRoot = this.attachShadow({mode: 'open'});
shadowRoot.innerHTML = element;
```

How can I use `ShadyCSS.prepareTemplate(element, 'my-element');` now?

**Comment by tuespetre** [comment]
This is something similar to what we're currently using:

```
const makeTemplate = function (strings, ...substs) {
    const html = '';
    for (let i = 0; i < substs.length; i++) {
        html += strings[i];
        html += substs[i];
    }
    html += strings[strings.length - 1];
    const template = document.createElement('template');
    template.innerHTML = html;
    return template;
}

var template = makeTemplate`<style>...</style><div>...</div>`;
```

**Comment by lukasoppermann** [comment]
Thanks, this works quite well. However shouldn't this polyfill be capable of working with a template string as well?

**Comment by tuespetre** [comment]
I thought so at first. It would be more 'inviting' that way, IMO. If it could detect a string, make the template, apply the CSS extraction and className transforms, and return the resulting innerHTML that would be convenient. 👍

**Comment by lukasoppermann** [comment]
It could also just be a second function. That would be enough.

**Comment by derekshull** [comment]
This is works great!  Definitely what I was looking for.  Thanks @tuespetre

**Comment by treshugart** [comment]
Yep, definitely need this to make it simpler for libs like [Skate](https://github.com/skatejs/skatejs) that utilise a virtual DOM.

Currently you can create a template and prepare it and then get the css content from it, but that's requires a bit of effort.

**Comment by lukasoppermann** [comment]
Hey, @azakus is there any news on this? Would it me possible to make the `prepareTemplate` accept either a node (`<template>`) or a `string/template-string`? This way if you do not want to require html imports which has a pretty bad looking future (2 on hold 1 consideration), you could still use it without adding an additional function. 

The function above could just be added. Maybe @tuespetre could add a PR if you say it would probably be merged? I would also create the PR, if @tuespetre does not want to, but since you already created posted the function, I guess it would make sense.

**Comment by treshugart** [comment]
If you only need styles as a string, you could do something like this:

```js
const { ShadyCSS } = window;
const $template = Symbol();
const { HTMLElement } = window;
const { attachShadow } = HTMLElement.prototype;
const nativeShadowDomSupport = attachShadow && /native code/.test(attachShadow.toString());

function style (elem, css) {
  const style = `${<style>{css}</style>}`;
  if (nativeShadowDomSupport) {
    return style;
  }
  const template = elem[$template] || (elem[$template] = document.createElement('template'));
  template.innerHTML = style;
  ShadyCSS.prepareTemplate(template, elem.localName);
  return '';
}
```

**Comment by lukasoppermann** [comment]
Hey @treshugart I do also need a `<slot>`element. Anyway, I feel that the polyfill should allow for us to just use custom elements without using htmlimport as this is valid by the specs. This should be possible without adding a function to every element you write, to convert the template string to a template tag. 

I think this would be easy and cheap to add, please let me know if this assumption is wrong. 😉

**Comment by kevinpschaaf** [comment]
Just to add some status here, currently the `shadycss` polyfill only supports scoping styles _prototypically_ for an element (e.g., for _all_ instances of a given element type) via the `prepareTemplate` API by collecting styles from an element's template, shimming them, and adding a single stylesheet to the document that selects elements by tag name, hence they apply to all instances.  This is a massive performance optimization and simplification because the ability to support imperatively appending stylesheets to `shadowRoots` at instance time implies scoping _individual instances_, and this is significantly a.) more complex and b.) would be very hard to make performant.

That said, `shadycss` does already currently support a flavor of instance scoping via the custom properties shim, which in addition to the prototypical styles, also adds stylesheets scoped to individual instances by marking them with a monotonically increasing numbered class name used in the selectors.  To make that viable performance-wise it needs to implement a pretty complex style cache to avoid creating hundreds/thousands of stylesheets scoped to individual instances (but still could if there were indeed that many instances with different properties applied to them).  This would all need to be adapted to supporting addition of runtime-appended stylesheets also scoped to instances in a similar way with a cache sufficient to reduce the amount of duplicate styles that need to be shimmed and applied to the document.

Which is all to say... Yes, we hear you that it's a.) surprising that the polyfill "doesn't just work" per the native feature and b.) there are lots of great use cases that would open up by supporting it.

At the same time, please understand that just implementing per the spec without regard to performance would likely result in something that's unusable for production (shady dom is specifically trying to be as close to the spec as possible while still being production-viable), and that supporting this in a performant way will take some considerable effort.

**Comment by azakus** [comment]
Deduplicated against #134
